listener {
    timeout = 900
    on-timeout = ddcutil setvcp 10 0 
    on-resume = ddcutil setvcp 10 90 
}

listener {
    timeout = 900
    on-timeout = brightnessctl -s set 0  # Save current brightness and set to 0
    on-resume = brightnessctl -r         # Restore previous brightness on activity
}

listener {
    timeout = 300
    on-timeout = hyprlock
}


