#!/usr/bin/sh

sxhkd & 
polybar & 
dunst &
picom -b &
feh --bg-fill ~/Pictures/naviaP.jpg &
xsetroot -cursor_name left_ptr

if [[ "$(xrandr | grep 'HDMI1 connected')" ]]; then
    bspc monitor HDMI1 -d        
    bspc monitor eDP1 -d  
    bspc config top_padding 0
else
    bspc monitor eDP1 -d        
    bspc monitor HDMI1 -d  
fi

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='focused:^1'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a code-oss desktop='^2'
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a 'Youtube Music' desktop='^5'

bspc monitor eDP1 -s HDMI1
