#!/usr/bin/sh

xsetroot -cursor_name left_ptr
# setxkbmap -option ctrl:swapcaps

if xrandr -q | grep 'HDMI-1-1 connected'; then
    xrandr --output HDMI-1-1 --mode 3440x1440 --primary --left-of eDP-1 --output eDP-1 --mode 1920x1080
    bspc monitor eDP-1 -d 1 2
    bspc monitor HDMI-1-1 -d 3 4 5 6 7
    bspc config top_padding 0
    # bspc monitor eDP-1 -s HDMI-1
else
    xrandr --output eDP-1 --mode 1920x1080 --primary --output HDMI-1-1 --off
    bspc monitor -d 1 2 3 4 5 6 7 
fi

sxhkd & 
polybar example --config=~/.config/polybar/config.ini &
dunst &
picom -b &
xsetroot -cursor_name left_ptr
feh --bg-fill ~/Pictures/sclerawall.jpg &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config top_padding 40
bspc config focused_border_color "#ffffff"
bspc config border_width         3
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
