#!/usr/bin/sh

sxhkd & 
polybar & 
dunst &
picom -b &
feh --bg-fill ~/Pictures/sclera.jpg &
xsetroot -cursor_name left_ptr

if [[ "$(xrandr | grep 'HDMI-1 connected')" ]]; then
    bspc monitor eDP-1 -d 
    bspc monitor HDMI-1 -d      
    bspc config top_padding 0
    # bspc monitor eDP-1 -s HDMI-1
else
    bspc monitor -d        
fi

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a discord desktop='^4'
bspc rule -a code-oss desktop='^2'
bspc rule -a jetbrains-studio desktop='^2'
bspc rule -a 'Youtube Music' desktop='^5'

